### ISSUE TITLE
Protobuild.exe Triggers Avira anti Virus

### ISSUE THREAD

**Issue by AxiomVerge** [hach-que/Protobuild#81]
When I synced the most recent protobuild.exe, Avira brought up a message box saying it had detected the TR/Dropper.msil.gen Trojan.  Probably a false positive, but, seemed worth a mention.

**Comment by hach-que** [comment]
There's unfortunately nothing I can do about this (it sounds like the
antivirus in question is a pile of junk if it's signature matches are this
broad).

It's most likely because the Protobuild executable contains another
compressed library which is decompressed and loaded at runtime.  This is
done to ensure the binary file remains as small as possible for storage in
Git repositories.

**Comment by tomspilman** [comment]
Thanks... that is what I suspected as well.  This at least is now a record that it has come up and that it is nothing to worry about.

**Comment by hach-que** [comment]
Closing this as there's nothing to action.
