### ISSUE TITLE
New package manager discussion

### ISSUE THREAD

**Issue by DDReaper** [hach-que/Protobuild#83]
Great stuff on the package Manager @hach-que , been testing it this morning and it work's well.

A few questions to come to mind:
* Any plans for a GUI? (both external to VS / MD / XS and within)
* How about reference updates?
* What about package updates / fixes and would it handle not overwriting altered local files?
* It seems to require GIT installed.  As a highlight mentions you don't need GIT, this seems contradictory
* Is it possible to switch the source to a private fork whilst retaining the package reference? (couldn't see anything in the docs about using an alternate source)

Over all I think it is fantastic as a way to deliver whole packages or new templates.  Just not quite sure on the references part (but it is a great start)

**Comment by hach-que** [comment]
> Any plans for a GUI? (both external to VS / MD / XS and within)

I did have plans for a GUI (at the very least a "start with a template" dialog), but I haven't had a lot of time to work on it.

> How about reference updates?

Do you mean if the referenced branch or version changes after performing Git pull on your source code (i.e. another developer upgrades a library version)?  We're actually not doing anything automatically here at the moment (you can delete the folder and run --generate again to get the latest version).  We probably should, but that introduces problems with the next item.

> What about package updates / fixes and would it handle not overwriting altered local files?

We don't touch or modify the referenced library's files (outside Protobuild's normal behaviour anyway).  The exception is when you ask to generate for a platform that there are no binary versions available for; in this case we remove the binary versions and clone the source code.

> It seems to require GIT installed. As a highlight mentions you don't need GIT, this seems contradictory

It requires Git for source packages only.  If you provide binary packages for your library, then Git isn't required.  You should never add a library's folder to source control though (regardless of SCM), so the worst case is you'll end up with a Git repository in an untracked and ignored folder in Perforce / Mercurial / SVN.

> Is it possible to switch the source to a private fork whilst retaining the package reference? (couldn't see anything in the docs about using an alternate source)

You'd have to change the URL in the ModuleInfo.xml file.  I haven't had a very good experience with "package name" + "repository URLs managed elsewhere" with NuGet at work, especially since the externally managed repository URLs would play havok with the build servers (with multiple builds running).  For that reason, I stuck with the Git submodule approach and retained the full URL in the package reference.

Thanks for the feedback :)

**Comment by hach-que** [comment]
I should add that binary packages are intended to represent a built commit; the version number of a binary package is an SHA1 hash.

Branches (like the Git equivalent) can be used to indicate human versioning (like creating a branch "v4.0.1").

**Comment by hach-que** [comment]
Just an update: The latest version of Protobuild will now cache source packages as well.

This means that when you use MonoGame as a package, even if you are using it in source form (where binaries aren't available), it's only downloaded once.  When you create a second or third project using packages, no downloads are necessary (and you can create new projects based on a previously used template entirely offline).

Protobuild will still attempt to perform "git fetch" before checkout (to make sure it has all the latest commits available), but if it fails or there's no internet connection then it's ignored and continues using what it has available in the cache.

**Comment by hach-que** [comment]
Package upgrades can now be done with the `--upgrade` command, like so:

```
mono Protobuild.exe --upgrade http://protobuild.org/hach-que/xunit
```

For source-based packages, this will delete any modifications made to the source code.

**Comment by hach-que** [comment]
So I did some more work on this, you can now use `--upgrade-all` to upgrade all packages in your module.

In addition, you can also configure package redirections.  This allows you to redirect package URLs (either used directly in your module or any of it's submodules) to a different URL.

For an extended example, this would allow you to redirect a MonoGame package reference to a modified version of MonoGame, even if the MonoGame package is being used in a library which you're consuming.  Or as a diagram:

```
Original:

Your project -> Third-party library (ref'd as http://protobuild.org/someone/ThirdParty) -> MonoGame (ref'd as http://protobuild.org/MonoGame/MonoGame)

With package redirection:

Your project -> Third-party library (ref'd as http://protobuild.org/someone/ThirdParty) -> MonoGame (ref'd as http://protobuild.org/You/MonoGameFork)
```

Package redirection can be configured either per command invocation with `--redirect`, or at a user level inside a `protobuild-redirects.txt` file residing in Application Data.  I've updated the documentation both for the new upgrade commands and for package redirections, which you can read about at http://protobuild.readthedocs.org/en/latest/package_management_protobuild.html#redirecting-package-urls.

**Comment by hach-que** [comment]
(On a side note, one of the next things I want to do on this is to allow you to redirect package URLs to a local Git repository on your machine, which would allow you to redirect all projects to a common version of MonoGame that you have locally)

**Comment by hach-que** [comment]
Redirecting to Git repos locally on your machine is now supported as well: http://protobuild.readthedocs.org/en/latest/package_management_protobuild.html#redirecting-package-urls

**Comment by hach-que** [comment]
I'm going to close this task as I don't believe there's anything left actionable here.
