### ISSUE TITLE
Linux + Stable Binaries

### ISSUE THREAD

**Issue by ashes999** [hach-que/Protobuild#94]
Hi,

I develop primarily on Linux. I noticed the main download link, links to github (`raw`/`master`). Is this really a Linux executable that I can run with `mono ProtoBuild.exe`?

Can you please link to a well-tested release version? I use multiple machines, and if I install ProtoBuild a few days apart, I won't be able to tell if they're the same version or not.

GitHub has a good releases feature. I don't know how much testing you do (automated / manual), but that's usually a good place to drop "stable" binaries.

**Comment by emarcotte** [comment]
Protobuild.exe is a .NET executable it works fine on linux... I use it all the time with the mono command you list.

**Comment by hach-que** [comment]
The Protobuild executable works on any platform (it has to because it gets stored in a repository for everyone to use).

`origin/master` is the latest, stable version.  We always run the full functional suite before updating Protobuild.exe in the root of this repository (which is what is linked to).  Development or experimental features always reside in feature branches until they are stable enough for every day use (unless they are something entirely new and don't impact current functionality).

Because Protobuild gets stored in your repository (and tracked by Git), you shouldn't have different binary versions per computer.  You might have different versions per repository / submodule, but this does not matter because we provide a very strong guarantee of forward and backward compatibility in this setup; modules can call submodules that have a different version of Protobuild, and everything will work.

**Comment by hach-que** [comment]
I've updated http://protobuild.readthedocs.org/en/latest/getting_started.html to indicate that you should be storing Protobuild.exe in source control (and that it is cross-platform).  I'm going to close this issue for now; if you have more questions feel free to open it again.

**Comment by ashes999** [comment]
Thanks for clarifying and updating your docs appropriately.
